# The URL the site will be built for
base_url = "https://historischerverein.surge.sh/"
theme = "wanderlust"
generate_rss = true
title = "Freileben"
description = "Dein erfülltes Leben"
compile_sass = false
build_search_index = true


taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
author = "Dave"
wanderlust_menu = [
    {url = "$BASE_URL", name = "Startseite"},
    {url = "$BASE_URL/about", name = "Über uns"},
    {url = "$BASE_URL/contact", name = "Kontakt"}
]
wanderlust_social = [
    {url = "https://twitter.com", icon="name='twitter' type='logo'"},
    {url = "$BASE_URL/rss.xml", icon="name='rss'"}
]


#4708943f62f02e9b6ff63ff923751544d7c3e1c4