# The URL the site will be built for
base_url = "https://hist.staneks.de"
theme = "wl"
feed_filenames = ["rss.xml"]
title = "Historischer Verein Oberammergau"
description = "Die Website des Historischen Vereins Oberammergau. Wir freuen uns auf Sie!"
compile_sass = false
build_search_index = true
generate_feeds = true
default_language = "de"


taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[search]
index_format = "elasticlunr_json"

[extra]
author = "Simeon"
wanderlust_menu = [
    {url = "$BASE_URL/", name = "Startseite"},
    {url = "$BASE_URL/blog", name = "Beiträge"},
    {url = "$BASE_URL/publikationen", name = "Publikationen"},
    {url = "$BASE_URL/ueber-uns", name = "Über uns"},
    {url = "$BASE_URL/kontakt", name = "Kontakt"}
]
wanderlust_social = [
    {url = "https://twitter.com", icon="name='twitter' type='logo'"},
    {url = "$BASE_URL/rss.xml", icon="name='rss'"}
]


#4708943f62f02e9b6ff63ff923751544d7c3e1c4
