backend:
  name: github
  repo: SimeonLukas/HV-Homepage
media_folder: "/static/images/uploads" 
public_folder: "/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    format: toml-frontmatter
    label: "Blog" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Schlagworte und Kategorien"
        name: "taxonomies"
        widget: "object"
        fields: 
        - label: "Kategorien"
          name: "categories"
          widget: "list"
          default: ["Newsletter"]
        - label: "Schlagworte"
          name: "tags"
          widget: "list"
          default: ["Aktuell"]
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
        - label: "Thumbnail"
          name: "image"
          widget: "image"
          width: 400